version: '3'
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./plex/config:/config:rw
      - ./plex/transcode:/transcode:rw
      - ./media/downloads/tvshows:/data/tvshows:rw
      - ./media/downloads/movies:/data/movies:rw
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./radarr/config:/config
      - ./media/downloads/movies:/movies:rw
      - ./media/downloads/movies:/downloads:rw
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:
      - ./sonarr/config:/config:rw
      - ./media/downloads/tvshows:/tv:rw
      - ./media/downloads/tvshows:/downloads:rw
    environment:
      - TZ=America/Sao_Paulo
      - PGID=1000
      - PUID=1000
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    ports:
      - 6767:6767
    volumes:
      - ./bazarr/config:/config:rw
      - ./media/downloads/tvshows:/tv:rw
      - ./media/downloads/movies:/movies:rw
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - 9117:9117
    volumes:
      - ./media/downloads:/downloads:rw
      - ./jackett/config:/config:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
      - PGID=1000
      - PUID=1000
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config:rw
      - ./media/downloads:/downloads:rw
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
