version: '3'
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./plex/config:/config:rw
      - ./plex/transcode:/transcode:rw
      - ./media/downloads/tvshows:/data/tvshows:rw
      - ./media/downloads/movies:/data/movies:rw
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./radarr/config:/config
      - ./media/downloads/movies:/movies:rw
      - ./media/downloads:/downloads:rw
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:
      - ./sonarr/config:/config:rw
      - ./sonarr/tv:/tv:rw
      - ./media/downloads/tvshows:/downloads:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
      - PGID=1000
      - PUID=1000
    links:
      - jackett
      - transmission
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - 9117:9117
    volumes:
      - ./media/downloads:/downloads:rw
      - ./jackett/config:/config:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
      - PGID=1000
      - PUID=1000
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./transmission/config:/config:rw
      - ./media/downloads:/downloads:rw
      - ./torrents:/watch:rw
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
