version: '3'
services:
  plex:
    image: linuxserver/plex
    network_mode: host
    volumes:
      - ./plex/config:/config:rw
      - ./plex/transcode:/transcode:rw
      - ./media/tvshows:/data/tvshows:rw
      - ./media/movies:/data/movies:rw

  radarr:
    image: linuxserver/radarr
    volumes:
      - ./radarr/config:/config
      - ./media/movies:/movies:rw
      - ./media/downloads:/downloads:rw
    ports:
      - 7878:7878

  sonarr:
    image: linuxserver/sonarr
    ports:
      - 8989:8989
    volumes:
      - ./sonarr/config:/config:rw
      - ./media/tvshows:/tv:rw
      - ./media/downloads:/downloads:rw

  bazarr:
    image: linuxserver/bazarr
    ports:
      - 6767:6767
    volumes:
      - ./bazarr/config:/config:rw
      - ./media/tvshows:/tv:rw
      - ./media/movies:/movies:rw

  jackett:
    image: linuxserver/jackett
    ports:
      - 9117:9117
    volumes:
      - ./media/downloads:/downloads:rw
      - ./jackett/config:/config:rw
      - /etc/localtime:/etc/localtime:ro

  qbittorrent:
    image: linuxserver/qbittorrent
    environment:
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config:rw
      - ./media/downloads:/downloads:rw
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
